
### 第一次编译

准备环境
```
sudo apt-get update
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
```

下载源码
```
git clone https://github.com/coolsnowwolf/lede
```

```
cd ~/lede

# sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
# echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
# echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
# sed -i '$a src-git openclash https://github.com/vernesong/OpenClash' feeds.conf.default
```

```
cd ~/lede
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
```

```
cd ~/lede

# sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate

rm -rf feeds/luci/themes/luci-theme-argon
rm -rf feeds/luci/applications/luci-app-dockerman
rm -rf feeds/packages/multimedia/aliyundrive-fuse
rm -rf feeds/luci/applications/luci-app-aliyundrive-fuse
rm -rf feeds/packages/multimedia/aliyundrive-webdav
rm -rf feeds/luci/applications/luci-app-aliyundrive-webdav

git clone https://github.com/kongfl888/luci-app-adguardhome.git package/luci-app-adguardhome
git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
git clone https://github.com/jerrykuku/luci-app-argon-config package/luci-app-argon-config
svn co https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman package/luci-app-dockerman
svn co https://github.com/messense/aliyundrive-fuse/trunk/openwrt/aliyundrive-fuse feeds/packages/multimedia/aliyundrive-fuse
svn co https://github.com/messense/aliyundrive-fuse/trunk/openwrt/luci-app-aliyundrive-fuse feeds/luci/applications/luci-app-aliyundrive-fuse
svn co https://github.com/messense/aliyundrive-webdav/trunk/openwrt/aliyundrive-webdav feeds/packages/multimedia/aliyundrive-webdav
svn co https://github.com/messense/aliyundrive-webdav/trunk/openwrt/luci-app-aliyundrive-webdav feeds/luci/applications/luci-app-aliyundrive-webdav

svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash package/luci-app-openclash
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/brook package/brook
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/chinadns-ng package/chinadns-ng
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/tcping package/tcping
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/trojan-go package/trojan-go
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/trojan-plus package/trojan-plus
svn co https://github.com/xiaorouji/openwrt-passwall/branches/luci/luci-app-passwall package/luci-app-passwall
svn co https://github.com/xiaorouji/openwrt-passwall2/trunk/luci-app-passwall2 package/luci-app-passwall2
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/xray-core package/xray-core
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/xray-plugin package/xray-plugin
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/ssocks package/ssocks
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/hysteria package/hysteria
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/v2ray-plugin package/v2ray-plugin
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/v2ray-core package/v2ray-core
svn co https://github.com/xiaorouji/openwrt-passwall/trunk/dns2tcp package/dns2tcp
svn co https://github.com/fw876/helloworld/trunk/v2ray-geodata package/v2ray-geodata
svn co https://github.com/fw876/helloworld/trunk/naiveproxy package/naiveproxy
svn co https://github.com/fw876/helloworld/trunk/sagernet-core package/sagernet-core
svn co https://github.com/fw876/helloworld/trunk/shadowsocks-rust package/shadowsocks-rust
svn co https://github.com/fw876/helloworld/trunk/shadowsocksr-libev package/shadowsocksr-libev
svn co https://github.com/fw876/helloworld/trunk/luci-app-ssr-plus package/luci-app-ssr-plus
svn co https://github.com/fw876/helloworld/trunk/simple-obfs package/simple-obfs
svn co https://github.com/fw876/helloworld/trunk/trojan package/trojan

./scripts/feeds update -a
./scripts/feeds install -a
```

```
make menuconfig
```

下载dl库
```
make -j8 download V=s
```

开始编译（-j1 后面是线程数。第一次编译推荐用单线程）
```
make -j1 V=s
```

### 第二次编译

```
git pull
./scripts/feeds update -a && ./scripts/feeds install -a
make defconfig
make -j8 download
```

开始编译（n=线程数+1，例如4线程的I5填-j5）
```
make -j$(($(nproc) + 1)) V=s
```

### 需要重新配置

```
rm -rf ./tmp && rm -rf .config
make menuconfig
```

开始编译（n=线程数+1，例如4线程的I5填-j5）
```
make -j$(($(nproc) + 1)) V=s
```

### 安装选项

```
	Target Images  --->
		[ ] tar.gz
		[ ] Build GRUB images
		[ ] GZip images
		(32) Kernel partition size (in MB)
		(480) Root filesystem partition size (in MB)
	Base system  --->
		[*]     Build with DHCPv6 support
	Extra packages  --->
		<*> autocore
		<*> automount
		<*> autosamba
		< > ipv6helper
	LuCI  --->
		3. Applications  --->
			<*> luci-app-accesscontrol
			< > luci-app-adguardhome
			< > luci-app-aliyundrive-fuse
			< > luci-app-aliyundrive-webdav
			< > luci-app-argon-config
			<*> luci-app-arpbind
			<*> luci-app-autoreboot
			<*> luci-app-ddns
			< > luci-app-diskman
			< > luci-app-dockerman
			<*> luci-app-filetransfer
			-*- luci-app-firewall
			<*> luci-app-ipsec-vpnd
			< > luci-app-n2n
			< > luci-app-netdata
			< > luci-app-nfs
			< > luci-app-openclash
			< > luci-app-passwall
			< > luci-app-passwall2
			< > luci-app-qbittorrent
			<*> luci-app-ssr-plus
			<*> luci-app-ttyd
			<*> luci-app-turboacc
			<*> luci-app-upnp
			<*> luci-app-vlmcsd
			<*> luci-app-vsftpd
		4. Themes  --->
			< > luci-theme-argon
	Network  --->
		< > iperf3
		< > snmpd
	Utilities  --->
		< > open-vm-tools
	Kernel modules  --->
		Network Support  --->
			< > kmod-tun (openclash依赖)

make defconfig
./scripts/diffconfig.sh > seed.config
```
